---
title: "Painel de Monitoramento da Dengue - São Caetano do Sul"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup,,  include=FALSE}
require(flexdashboard) 
require(foreign) 
require(tidyverse) 
require(lubridate)
require(plotly)
require(knitr)
require(DT)
require(gapminder)
require(reticulate)
require(dplyr)

infodengue_scs <- read_csv("infodengue_2012-2023.csv")
sinan_scs <- read_csv("sinan_2012-2021")

```

Row {data-height=150}
-----------------------------------------------------------------------

### Chart A

```{r}
#BLOCO 1
estatistica_2023 <- infodengue_scs |>
  filter(year(data_iniSE) == 2023)

total_notif <- sum(estatistica_2023$casos)
  
valueBox(total_notif,
caption = "Total de casos notificados",
color = "primary",
icon = "fa-pencil")
```
###
```{r}
#BLOCO 2
estatistica_2023 <- infodengue_scs |>
  filter(year(data_iniSE) == 2023)

media_casos <- round(mean(estatistica_2023$casos), 1)

valueBox(media_casos,
caption = "Média de casos notificados por semana",
color = "success",
icon = "fa-info")
```
###
```{r}
#BLOCO 3
estatistica_2023 <- infodengue_scs |>
  filter(year(data_iniSE) == 2023)

total_estimado <- sum(estatistica_2023$casos_est)

valueBox(total_estimado,
caption = "Total de casos estimados",
color = "warning",
icon = "fa-exclamation")
```

Row {data-height=650}
-----------------------------------------------------------------------
### Diagrama de Controle da Dengue em 2023

```{r, fig.width=12, fig.height=6}
nao_epidemic <- c(2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023)

dengue_ano <- infodengue_scs |>
  filter(year(data_iniSE) == 2023) |>
  mutate(sem_epi = epiweek(data_iniSE))

dengue_stat <- infodengue_scs |>
  filter(year(data_iniSE) %in% nao_epidemic) |>
  mutate(sem_epi = epiweek(data_iniSE)) |>
  group_by(sem_epi) |>
  summarise(
    n = n(),
    media = mean(p_inc100k, na.rm = TRUE), 
    desvio = sd(p_inc100k, na.rm = TRUE) , 
    sup = media + 2 * desvio,
    inf = media - 2 * desvio
  )

ggplot(data = dengue_stat,
  aes(x = sem_epi, y = media)) +
  stat_smooth(
    aes(color = 'cor_incidencia_media'), size = 1.2,
    se = FALSE,
    span = 0.2
  ) +
  
  stat_smooth(
    aes(y = sup, color = 'cor_limite'), size = 1.2,
    se = FALSE,
    span = 0.2
  ) +
  
  geom_col(data = dengue_ano,
    aes(y = p_inc100k, fill = 'cor_incidencia'), 
    alpha = 0.4) +
  scale_x_continuous(breaks = 1:53, expand = c(0, 0)) +
  labs(x = 'Semana Epidemiológica',
       y = 'Incidência (casos por 100 mil habitantes)',
       title = '') +
  theme_classic() +
  scale_color_manual(
    name = "",
    values = c('cor_incidencia_media' = 'darkblue', 'cor_limite' = 'red'), 
    labels = c("Incidência média de casos", "Limite superior")
  ) +
  scale_fill_manual(
    name = "",
    values = c('cor_incidencia' = 'deepskyblue'), labels = "Incidência de dengue em 2023"
  ) 

```

Row {data-height=400}
-----------------------------------------------------------------------
### Tabela

```{r}
tabela1 <- infodengue_scs |>
  mutate(incidencia = round(p_inc100k, digits = 1), 
         temperatura = round(tempmed, digits = 0), 
         umidade = round(umidmed, digits = 0),
         mes_ano = paste0(day(data_iniSE),"-",
                          month(data_iniSE),'-',year(data_iniSE)))

tabela2 <- tabela1 |>
filter(year(data_iniSE) == 2023) |>
mutate(sem_epi = epiweek(data_iniSE)) |>
select(mes_ano, sem_epi, casos, casos_est, incidencia, temperatura, umidade) |>
rename("Data de Início" = mes_ano, 
       "Semana Epidemiológica" = sem_epi, 
       "Casos Notificados" = casos, 
       "Casos Estimados" = casos_est, 
       "Incidência" = incidencia, 
       "Temperatura Média (°C)" = temperatura, 
       "Umidade Média (%)" = umidade)

datatable(tabela2,
options = list(pageLength = 5))

```

Row {data-height=650}
-----------------------------------------------------------------------
### Série Histórica - 2012 a 2021

```{r, fig.width=12, fig.height=6}

dengue_grafico <- sinan_scs |> 
  mutate(
  DT_NOTIFIC = ymd(DT_NOTIFIC), 
  sem_epi = epiweek(DT_NOTIFIC), 
  ano_epi = epiyear(DT_NOTIFIC), 
  mes = month(DT_NOTIFIC), 
  NU_ANO = as.numeric(NU_ANO)
)

grafico_1 <- dengue_grafico |>
  count(ano_epi, sem_epi) |>
  ggplot(aes(
    x = sem_epi,
    y = n,
    color = factor(ano_epi)
  )) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  xlab("\nSemana Epidemiológica") + 
  ylab("Casos Notificados") +
  scale_color_discrete("Ano") +
  scale_x_continuous(breaks = c(1, seq(5, 50, 5))) 
ggplotly(grafico_1)

```
